name: memorystone
main: cljminecraft.ClojurePlugin
version: 2.0.0
website: http://www.dats.co.za
author: CmdrDats
description: Memory Stone v2, Clojure port.
depend: [cljminecraft]
class-loader-of: cljminecraft
