name: memorystone
main: cljminecraft.ClojurePlugin
version: 2.0.0
website: http://github.com/CmdrDats/clj-memorystone
author: CmdrDats
description: Memory Stone v2, Clojure rewrite.
depend: [cljminecraft]
class-loader-of: cljminecraft